In [33]:
import pandas as pd

In [34]:
df_orders = pd.read_parquet('../Dataset limpiado/ordenes_de_trabajo.parquet')
df_age_equipment = pd.read_parquet('../Dataset limpiado/age_equipment_limp.parquet')
df_mechanic = pd.read_parquet('../Dataset limpiado/mechanic_limp.parquet')

In [35]:
df_orders.head(3)

,equipment,operation,wo_type,base_model,problem_desc,failure_desc,cause_desc,action_desc,mechanic,date,downtime_gross,pit_coverage,real_downtime,parts_cost,repair_hours,waiting_hours,changed_pcs,days_between_failures
0,100268,BIND LEG,Corrective Maintenance,VF2500,It sews with defect / Cose con defecto,Machine head failure stopping sewing / Falla ...,Misadjusted machine head teeth / Dientes de ca...,Adjust machine head teeth / Ajustar dientes de...,Jaime Rivera,2023-10-03,1.25,0.0,1.25,16.81,1.25,0.0,1,81.0
1,100268,BIND LEG,Corrective Maintenance,VF2500,It sews with defect / Cose con defecto,Machine head failure stopping sewing / Falla ...,Misadjusted machine head teeth / Dientes de ca...,Adjust machine head teeth / Ajustar dientes de...,Jaime Rivera,2023-10-03,1.25,0.0,1.25,16.81,1.25,0.0,1,0.0
2,100268,BIND LEG,Corrective Maintenance,VF2500,It sews with defect / Cose con defecto,Machine head failure stopping sewing / Falla ...,Misadjusted machine head needle bar / Barra de...,Adjust machine head teeth / Ajustar dientes de...,Jaime Rivera,2024-01-17,3.00,3.0,0.00,12.50,2.00,1.0,2,106.0

In [36]:
df_age_equipment.head(3)

   equipment  age
0    1014059   22
1    1156767   19
2    1011680   22

In [37]:
df_mechanic.head(3)

                      mechanic  antiquity
0  RIVAS TORRES CARLOS ANTONIO         19
1           Marvin Betancourth         18
2               JUAN BAAK CHIN         17

### Unimos 3 datasets a uno.

In [38]:
df = pd.merge(df_orders, df_age_equipment, on='equipment', how='inner')
df = pd.merge(df, df_mechanic, on='mechanic', how='inner')

In [39]:
df['mechanic'] = df['mechanic'].astype('category')

In [40]:
variables = pd.DataFrame(columns=['Variable', 'Número de valores unicos', 'Tipo','Valores'])
for i, var in enumerate(df.columns):
    variables.loc[i] = [var, df[var].nunique(), df[var].dtype,df[var].unique().tolist()]

variables

,Variable,Número de valores unicos,Tipo,Valores
0,equipment,6539,int64,"[100268, 102205, 116645, 116737, 151117, 17448..."
1,operation,59,category,"[BIND LEG, HEM BOTTOM, TOP STITCH, SEW ELASTIC..."
2,wo_type,7,category,"[Corrective Maintenance, Calibration, Breakdow..."
3,base_model,119,category,"[VF2500, VG2711, VF2560, VC2700, VC2711, VF240..."
4,problem_desc,24,category,"[It sews with defect / Cose con defecto, It do..."
5,failure_desc,37,category,[Machine head failure stopping sewing / Falla...
6,cause_desc,279,category,[Misadjusted machine head teeth / Dientes de c...
7,action_desc,278,category,[Adjust machine head teeth / Ajustar dientes d...
8,mechanic,176,category,"[Jaime Rivera, JERONIMO FUNEZ, Fabit Aranda, C..."
9,date,501,datetime64[ns],"[2023-10-03 00:00:00, 2024-01-17 00:00:00, 202..."
10,downtime_gross,380,float64,"[1.25, 3.0, 2.0, 1.5, 3.083333333, 0.583333333..."
11,pit_coverage,363,float64,"[0.0, 3.0, 2.0, 1.5, 1.42, 0.58, 1.0, 1.67, 0...."
12,real_downtime,546,float64,"[1.25, 0.0, 0.08, 0.083333333, 0.003333333, -0..."
13,parts_cost,6247,float64,"[16.81, 12.5, 5.75, 0.0, 7.65, 1.0, 67.75, 68...."
14,repair_hours,270,float64,"[1.25, 2.0, 1.5, 1.416666667, 2.5, 0.583333333..."
15,waiting_hours,297,float64,"[0.0, 1.0, 0.083333333, 0.583333333, 2.0, 2.25..."
16,changed_pcs,14,int64,"[1, 2, 3, 0, 4, 9, 5, 7, 6, 10, 12, 8, 11, 14]"
17,days_between_failures,441,float64,"[81.0, 0.0, 106.0, 153.0, 21.0, 193.0, 32.0, 7..."
18,age,24,int32,"[6, 5, 3, 20, 22, 27, 23, 24, 12, 10, 4, 13, 2..."
19,antiquity,23,int64,"[5, 9, 13, 7, 19, 6, 8, 10, 18, 1, 17, 15, 12,..."

In [41]:
df.shape

(135027, 20)

#### Agregamos calendario: dia, semana, mes

In [42]:
if 'dia' not in df.columns:
    df['dia'] = df['date'].dt.to_period('D')

if 'semana' not in df.columns:
    df['semana'] = df['date'].dt.to_period('W')

if 'mes' not in df.columns:
    df['mes'] = df['date'].dt.to_period('M')

#### Guardamos el dataset unificado y sin valores faltantes.

In [43]:
df.to_parquet('../Dataset limpiado/dataset unificado.parquet')